apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: db-simple
  labels:
    run: db
spec:
  replicas: 1
  selector:
    matchLabels:
      run: db
  template:
    metadata:
      generateName: db-simple
      labels:
        run: db
        version: v0.1
    spec:
      restartPolicy: Always
      containers:
        - name: db-simple
          image: mysql
          imagePullPolicy: Always
          ports:
            - name: db-mysql
              containerPort: 3306
