apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: web
  name: web
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: web
status:
  loadBalancer: {}
